spring.application.name=project
tmdb.api.key = f0a397f188e2de2ecf3a169bb7249343
server.port = 9090
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true
